CREATE DATABASE LIBRARY_DB;
USE LIBRARY_DB;

-- PUBLISHER
CREATE TABLE PUBLISHER(
P_NAME VARCHAR(255) PRIMARY KEY,
P_ADDRESS TEXT,P_PHONE VARCHAR(100));

-- BOOKS
CREATE TABLE BOOKS(
B_ID INT PRIMARY KEY,
B_TITLE VARCHAR(200),B_PUBLISHER_NAME VARCHAR(255),
FOREIGN KEY(B_PUBLISHER_NAME) REFERENCES PUBLISHER(P_NAME)
);

-- AUTHORS
CREATE TABLE AUTHORS(
B_AUTHOR_ID INT PRIMARY KEY AUTO_INCREMENT,
BOOK_ID INT,AUTHOR VARCHAR(200),
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(B_ID)
);

-- LIBRARY BRANCHES
CREATE TABLE BRANCHES(
BRANCH_ID INT PRIMARY KEY AUTO_INCREMENT,
BRANCH_NAME VARCHAR(200),BRANCH_ADDRESS TEXT
);

-- BOOKS COPIES
CREATE TABLE COPIES(
COPY_ID INT PRIMARY KEY AUTO_INCREMENT,
COPY_BOOK_ID INT,BRANCHID INT,NUM_OF_COPIES INT,
FOREIGN KEY(COPY_BOOK_ID) REFERENCES BOOKS(B_ID),
FOREIGN KEY(BRANCHID) REFERENCES BRANCHES(BRANCH_ID)
);

-- BORROWER
CREATE TABLE BORROWER(
CARD_NUM INT PRIMARY KEY,B_NAME VARCHAR(200),
B_ADDRESS VARCHAR(200),B_PHONE VARCHAR(100)
);

-- LOANS
CREATE TABLE LOANS(
LOAN_ID INT PRIMARY KEY AUTO_INCREMENT,
L_BOOKID INT,L_BRANCHID INT,L_CARDNO INT,
L_DATEOUT DATE,L_DUEDATE DATE,
FOREIGN KEY(L_BOOKID) REFERENCES BOOKS(B_ID),
FOREIGN KEY(L_BRANCHID) REFERENCES BRANCHES(BRANCH_ID),
FOREIGN KEY(L_CARDNO) REFERENCES BORROWER(CARD_NUM)
);


-- CHECKING THE DATA IS CORRECTLY IMPORTED OR NOT
SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;
SELECT * FROM BORROWER;
SELECT * FROM BRANCHES;
SELECT * FROM COPIES;
SELECT * FROM LOANS;
SELECT * FROM PUBLISHER;

-- How many copies of the book titled "The Lost Tribe" are owned by the library branch whose name is "Sharpstown"
SELECT SUM(NUM_OF_COPIES) FROM BOOKS, COPIES, BRANCHES
WHERE BOOKS.B_ID = COPIES.COPY_BOOK_ID
AND COPIES.BRANCHID = BRANCHES.BRANCH_ID
AND BOOKS.B_TITLE = 'The Lost Tribe'
AND BRANCHES.BRANCH_NAME = 'Sharpstown';

-- How many copies of the book titled "The Lost Tribe" are owned by each library branch
SELECT BRANCHES.BRANCH_NAME,SUM(NUM_OF_COPIES) FROM BOOKS, COPIES, BRANCHES
WHERE BOOKS.B_ID = COPIES.COPY_BOOK_ID
AND COPIES.BRANCHID = BRANCHES.BRANCH_ID
AND BOOKS.B_TITLE = 'The Lost Tribe'
GROUP BY BRANCHES.BRANCH_NAME;

-- Retrieve the names of all borrowers who do not have any books checked out
SELECT B_NAME FROM BORROWER
LEFT JOIN LOANS
ON BORROWER.CARD_NUM = LOANS.L_CARDNO
WHERE LOANS.L_CARDNO IS NULL;

-- For each book that is loaned out from the "Sharpstown" branch and whose DueDate is 2/3/18, 
-- retrieve the book title, the borrower's name, and the borrower's address. 
SELECT BOOKS.B_TITLE,BORROWER.B_NAME,BORROWER.B_ADDRESS FROM LOANS
JOIN BOOKS ON LOANS.L_BOOKID = BOOKS.B_ID
JOIN BORROWER ON LOANS.L_CARDNO = BORROWER.CARD_NUM
JOIN BRANCHES ON LOANS.L_BRANCHID = BRANCHES.BRANCH_ID
WHERE BRANCHES.BRANCH_NAME = 'Sharpstown'
AND LOANS.L_DUEDATE = '2/3/18';

-- For each library branch, retrieve the branch name and the total number of books loaned out from that branch
SELECT BRANCHES.BRANCH_NAME,COUNT(*) AS TOTAL_NO_OF_BOOKS FROM LOANS
JOIN BRANCHES ON LOANS.L_BRANCHID = BRANCHES.BRANCH_ID
GROUP BY BRANCHES.BRANCH_NAME;

-- Retrieve the names, addresses, and number of books checked out for all borrowers who have more than five books checked out
SELECT BORROWER.B_NAME,BORROWER.B_ADDRESS,COUNT(*) FROM BORROWER
JOIN LOANS ON BORROWER.CARD_NUM = LOANS.L_CARDNO
GROUP BY BORROWER.CARD_NUM
HAVING COUNT(*) > 5;

-- For each book authored by "Stephen King", retrieve the title and the number of copies owned by the library branch whose name is "Central"
SELECT BOOKS.B_TITLE,COPIES.NUM_OF_COPIES FROM BOOKS
JOIN AUTHORS ON BOOKS.B_ID = AUTHORS.BOOK_ID
JOIN COPIES ON BOOKS.B_ID = COPIES.COPY_BOOK_ID
JOIN BRANCHES ON COPIES.BRANCHID = BRANCHES.BRANCH_ID
WHERE AUTHORS.AUTHOR = 'Stephen King'
AND BRANCHES.BRANCH_NAME = 'Central';
